from building import * 
import rtconfig

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []
group=[]


# Exclude montserrat fonts already provided by the SDK LVGL
src += [f for f in Glob('*.c') if 'montserrat' not in str(f)]

LOCAL_CCFLAGS = ''

group = DefineGroup('App_watch_demo_res', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
