from building import *
import os

cwd = GetCurrentDir()
src = []
inc = [
    cwd,
    os.path.join(cwd, 'main'),
    os.path.join(cwd, 'modules', 'mem')  # <--- 救命稻草：让 LVGL 能顺藤摸瓜找到 app_mem.h
]

# 核心魔法：在这里登记你需要编译的子文件夹！
# 如果你以后加了新文件夹，就在这里补一行
src.extend(SConscript(os.path.join(cwd, 'main/SConscript'), variant_dir="main", duplicate=0))
src.extend(SConscript(os.path.join(cwd, 'modules/SConscript'), variant_dir="modules", duplicate=0))
src.extend(SConscript(os.path.join(cwd, 'gui/SConscript'), variant_dir="gui", duplicate=0))
src.extend(SConscript(os.path.join(cwd, 'modules/mem/SConscript'), variant_dir="modules_mem", duplicate=0))
src.extend(SConscript(os.path.join(cwd, 'hal_port/SConscript'), variant_dir="hal_port", duplicate=0))
# src.extend(SConscript(os.path.join(cwd, 'gui/SConscript'), variant_dir="gui", duplicate=0)) # 等你建了 gui 文件夹再取消注释

# 2. 修复 lang_pack.h：加载多语言和字体资源
Execute(Mkdir('gui/resource/strings')) # 确保目录存在
Execute(Mkdir('gui/resource/fonts')) # 确保目录存在
src.extend(SConscript(os.path.join(cwd, 'gui/resource/strings/SConscript'), variant_dir="resource_strings", duplicate=0))
src.extend(SConscript(os.path.join(cwd, 'gui/resource/fonts/SConscript'), variant_dir="resource_fonts", duplicate=0))

group = DefineGroup('app', src, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = inc)
Return('group')